[providers]
python = "3.10"

[phases.setup]
aptPkgs = ["ffmpeg", "libsndfile1-dev"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[start]
cmd = "python app.py"

